### ISSUE TITLE
[bug] Note pane, some titles blurry

### ISSUE THREAD

**Issue by ChaseTramel** [johansan/notebook-navigator#200]
<img width="373" height="371" alt="Image" src="https://github.com/user-attachments/assets/a72a2c75-f568-4dcc-8c75-0f49f1f9931f" />

<img width="100" height="125" alt="Image" src="https://github.com/user-attachments/assets/a35e2f7b-58e1-4168-ac99-4acdc1366622" />

See attached photos. I'm using the Baseline theme.

Attempted turning off all plugins except Notebook Navigator, and the bug persisted. Persisted in AnuPpuccin and default theme as well.

**Comment by johansan** [comment]
Thanks will check it out. Which OS? Windows?

**Comment by ChaseTramel** [comment]
> Which OS? Windows?

Yes, Windows!

**Comment by johansan** [comment]
Can you try reset to the default font, let me know if it persists

**Comment by johansan** [comment]
I have implemented a possible fix for the next version, it will be released later today. Many thanks for your report, please try next version and see if it fixes it.

**Comment by ChaseTramel** [comment]
<img width="407" height="591" alt="Image" src="https://github.com/user-attachments/assets/cf5dca5a-32a7-49bf-b0ad-4ff3ade4ef33" />

Upon updating and reverting to default font, the issue persists.

**Comment by johansan** [comment]
Ok thanks. Looks like I have to find a way to replicate it myself. I have pcs with windows 11 but don't see the issue on them. But I will try and get back to you.

**Comment by johansan** [comment]
Ok I see the issue is that you use scaling on the display. I will try another thing and push out 1.4.19 later today.

**Comment by johansan** [comment]
1.4.19 is out now please give it a try. 👍

**Comment by ChaseTramel** [comment]
<img width="331" height="552" alt="Image" src="https://github.com/user-attachments/assets/c1772448-554c-48fb-9c20-483457fde094" />

Okay, progress! They now all look slightly blurry, instead of some looking crisp and some blurry. My husband can't even tell.

**Comment by johansan** [comment]
😂 ok at least going somewhere. Ok I will see what I can do with this.

**Comment by johansan** [comment]
What scaling do you use? 125%, 150% or 200%?

**Comment by ChaseTramel** [comment]
125%!

**Comment by johansan** [comment]
Ok then I think i solved it. 

I had a 10px spacer on top of all lists. When I fixed the file items then the spacer caused all to be incorrect. 

10px * 1.25 = 12.5 pixel offset for all items 

I will push 1.4.20 tomorrow hopefully we nail it this time. Thanks for your help!

**Comment by ChaseTramel** [comment]
Of course! Happy to help any way I can!

**Comment by Lelou123** [comment]
I would like to thank you so much for your effort in bringing this plugin and will be sure to buy you a coffe as soon as possible haha.
And sadly will be joining the theading, it improved a lot in the last updates and just lile @ChaseTramel mines is like this. Unlike her my scale is 100%. 

<img width="461" height="940" alt="Image" src="https://github.com/user-attachments/assets/ac802300-daaf-4130-9c9b-9a46ab0eede6" />

<img width="446" height="835" alt="Image" src="https://github.com/user-attachments/assets/86b1368b-a9a7-4d46-80de-524109fa4081" />

Comparing to the obsidian search

<img width="468" height="533" alt="Image" src="https://github.com/user-attachments/assets/2a0632b6-aea3-4f19-8ce0-e32dcb099c5d" />

**Comment by johansan** [comment]
> Unlike her my scale is 100%.

Thank you! You are actually also using scaling, but not in Windows but 110% Obsidian UI scaling. This helps me a lot to identify this. Now I can debug it myself.

**Comment by Lelou123** [comment]
>but 110% Obsidian UI scaling.

Great that this helps you out. Actualy i'm using 120%, if it helps my font is the default and set in 18. All the others are pretty much default, if there is anything else i can help just say the word!

**Comment by johansan** [comment]
🥳 SOLVED IT! For real this time! 🎉 Fix coming in next version! Together with an amazing new feature!

The trick was that I could replicate it myself on my PC with obsidian scaling

**Comment by Lelou123** [comment]
> 🥳 SOLVED IT! For real this time! 🎉 Fix coming in next version! Together with an amazing new feature!
> 
> The trick was that I could replicate it myself on my PC with obsidian scaling

Nicee cant wait to see, i'm loving to use this plugin in my flow

**Comment by johansan** [comment]
Please report back here after testing. Closing topic for now.

**Comment by ChaseTramel** [comment]
Yes, this solved my issues!

**Comment by johansan** [comment]
Glad to hear it!
