### ISSUE TITLE
Tags not showing and counted.

### ISSUE THREAD

**Issue by thehyperadvisor** [johansan/notebook-navigator#34]
I don’t think that the Tag lists are showing tags that are in the property “tag”. This might be because there’s no # on the tags in the property. 

I noticed because the native tag widget count shows more than what’s shown by your plugin for some of my tags.

**Comment by johansan** [comment]
Check so you use them right, in this format:

https://help.obsidian.md/tags
```
---
tags:
  - recipe
  - cooking
---
```
 I just pushed up version 1.2 it has many internal changes and improvements, and this works for me. Try updating to latest and report if it works.

**Comment by thehyperadvisor** [comment]
I'm comparing to what the native tags widget shows so I assume they're being used correctly. It's still showing the same after the update.

Have you tested with nested tags? I have tags like:
```
---
tags:
  - recipe/cajun
  - cooking/fried/chicken
---
```

**Comment by johansan** [comment]
Thanks. I will fix this. 👍

**Comment by johansan** [comment]
Weird when I add this to a note I get:

![Image](https://github.com/user-attachments/assets/59d5371a-2f1f-449f-a014-d57e5803677f)

Can you try using latest version and see what happens?

**Comment by thehyperadvisor** [comment]
It does show nested tags but the count does not match the count shown in the default tag plugin. 

See the images and compare the total count for each tag with nested tags. So I’m not sure it’s counting the upper and lower case tags with the same name correctly.

![Image](https://github.com/user-attachments/assets/834a014c-3eb0-4672-9729-9d45c35ef75e)
![Image](https://github.com/user-attachments/assets/1c91b976-904c-4e11-ad26-464e61d13b82)

**Comment by johansan** [comment]
Well which one is correct then? :) No need to change if mine is correct and the built-in is wrong? Can you see if you can spot why it differs?

**Comment by johansan** [comment]
I think the built-in counter might be incorrect and count case-dependent?

**Comment by thehyperadvisor** [comment]
Since your plugin separated upper and lower case tags in the nav pane previously and did not consolidate them I’m assuming it’s your plugin. 

If I use the tag “animal” in one note and then “Animal” in another note the count should be as 2. It should be showing the count of notes with the tag.

**Comment by johansan** [comment]
Yes and this is how I do it now. Please test it out and see if you can spot the differences. I.e. what makes it cause a difference, maybe test with some debug notes

**Comment by thehyperadvisor** [comment]
Okay. I’ll dig deeper. 

It’s just hard to believe the default tag counter is not correct but nothing is impossible. Plus the default show a higher count.

**Comment by thehyperadvisor** [comment]
I see why the count is higher in the default tag plugin. When it sees the "#animal" in the note and has "Animal" in the property, notice the case difference, it counts them as two(2). When the case is the same it counts them correctly. This is why the count is higher.

So you're plugin is handling this correctly. 

Thanks for checking on your end and getting me to dig deeper into this.

**Comment by johansan** [comment]
Super, thanks for reporting and taking the time to check it out!
