### ISSUE TITLE
[BUG] List Pane: some characters in the note title text got cut due to spacing on mobile

### ISSUE THREAD

**Issue by joellti** [johansan/notebook-navigator#600]
**Before submitting** Please check if your issue is already fixed in next version: [Features and bug fixes in next release](https://github.com/johansan/notebook-navigator/issues/363)

**Describe the bug**

As shown in the screenshot from phone, letters like g, j, p, q, y which are taller than others are cut at the bottom. Only the title text is affected, the same letters in the preview text looks fine.

![Image](https://github.com/user-attachments/assets/b24163b9-8f62-47b9-8465-9a5899b8b915)

**Steps to reproduce**

Create any note with title set to something containing these letters and open List Pane to view it.

**Expected behavior**

No cutting of these characters, potentially for all those tall ones.

**Environment:**

- Obsidian version: 1.10.3
- Plugin version: 1.8.8
- OS: Android

**Comment by johansan** [comment]
Thank you. I just slightly increased font size in list pane and missed this one, will fix it.

**Comment by johansan** [comment]
Thanks. Can you try to copy this main.js file to your notebook-navigator folder (vault/.obsidian/plugins/notebook-navigator) and take a new screenshot? I bumped line spacing a bit.

[main.js](https://github.com/user-attachments/files/23741853/main.js)

**Comment by joellti** [comment]
![Image](https://github.com/user-attachments/assets/704a50c7-ad14-481b-bc9a-36cebd2e46d7)

**Comment by joellti** [comment]
here is the screen shot that you asked. it seems the spacing is enough but somehow the cut-out is still there

**Comment by johansan** [comment]
Hm weird they both show the same spacing.

**Comment by johansan** [comment]
Ok I just checked my Android device and I cannot reproduce this

Any chance you have some custom font setting active on your device?

<img width="431" height="427" alt="Image" src="https://github.com/user-attachments/assets/cf2ead4e-7f92-461f-8d66-12838f21a78d" />

**Comment by johansan** [comment]
I did another tweak see if you can copy this file into notebook-navigator folder and send screenshot

[main.js](https://github.com/user-attachments/files/23743347/main.js)

**Comment by joellti** [comment]
I created a new vault with everything in stock state except for enabling this plugin. with the latest main.js, this is what looks like.

![Image](https://github.com/user-attachments/assets/ae1b2ee2-ce10-4c45-8751-3da8db19e13a)

**Comment by johansan** [comment]
Ok are you 100% sure you put main.js in the right folder, and do you reload after it? In both cases there were no visual differences but I have changed the layout

**Comment by joellti** [comment]
Yes I double checked and here is the main.js that I used for the new vault.

![Image](https://github.com/user-attachments/assets/ede2a057-c482-4ea7-be37-f082492efb2a)

![Image](https://github.com/user-attachments/assets/e1dff0bd-c087-4505-9ea4-4d065c6362b8)

**Comment by joellti** [comment]
I found the reason why it is happening to me. In the system setting `Font size and style` > `Font size`, it allows me to adjust the font size by 8 levels with level 1 being smallest and level 8 largest. The issue goes away after I reduce the size from level 5 to level 4. Still I don't know why it only affect the title line and only List pane.

**Comment by johansan** [comment]
Ok I will test a few things. First. Can you try changing to 2 title rows and see how it looks? Are both lines wrong or just the bottom one?

**Comment by joellti** [comment]
looks like it only effects the line right above the preview line.

![Image](https://github.com/user-attachments/assets/3a8339e7-1280-427a-9b95-75fbc9e36728)

**Comment by joellti** [comment]
here is another look with system font size increased further. it seems the box where the title lines are displayed in is not big enough to fit them.

![Image](https://github.com/user-attachments/assets/9dc69e4b-ff0c-4459-b896-e69ed6bfaa3b)

**Comment by johansan** [comment]
Ok I can reproduce it. And also it doesn't help replacing main.js since obsidian aggressively caches this file and just replacing it does nothing. 

I will push out an update with a bit of CSS cleanup, give that one a go once it's out and see if it looks different please

**Comment by johansan** [comment]
Ok I pushed out an update, but didn't work on my setup. I will follow this up in the future - when Android returns a 20px font when I request 14px everything in the plugin messes up.

**Comment by joellti** [comment]
I just tried 1.8.9 on my phone and the issue is still there as what happened to your setup. But I am glad that you were able to reproduce it. Look forward to your eventual fix. Thanks for your support.

**Comment by johansan** [comment]
I fixed this in next version. 👍

**Comment by johansan** [comment]
Notebook Navigator 1.9 is out now 👍
